### ISSUE TITLE
mulithreading support

### ISSUE THREAD

**Issue by lovesegfault** [dwrensha/fuzz-rustc#1]
On my machine this only uses one of the 64 available cores, which is a bit of a bummer.

**Comment by dwrensha** [comment]
Note that the `run_fuzzer.sh` script passes trailing arguments on to the underlying libfuzzer binary, so you can pass any of these options: https://llvm.org/docs/LibFuzzer.html#options . I think `-jobs` and `-workers` can help you achieve parallel fuzzing.

**Comment by dwrensha** [comment]
I verified that `-jobs` and `-workers` do indeed achieve parallelism, and I added a comment on the README: https://github.com/dwrensha/fuzz-rustc/commit/71c0118db7197ca00f078cd9d608de85d57bc94b. Thanks!
