### ISSUE TITLE
Is there a way to mute the error messages of rustc during fuzzing?

### ISSUE THREAD

**Issue by extf33** [dwrensha/fuzz-rustc#2]
Is there a way to mute the error messages of rustc during fuzzing?

**Comment by dwrensha** [comment]
Usually I run with 
```
./run-fuzzer.sh -jobs=20 -workers=20 -only_ascii=1
```
which diverts the error messages to files.

There might be a way to tell rustc to entirely suppress its error messages, but I am not familiar with it.

Consider also that when you do find a crash, you're going to want to see the error message for it.
