### ISSUE TITLE
empty profraw problem

### ISSUE THREAD

**Issue by lxyyyy09** [dwrensha/fuzz-rustc#6]
I'm trying to generate a .profraw file which can be later used to generate a .profdata file. 
I add `export LLVM_PROFILE_FILE="default.profraw"
export RUSTFLAGS="$RUSTFLAGS -C instrument-coverage"`into run-fuzzer.sh and I do get a .profraw file. But it is empty.
I am wondering what arguments or files should I change?Or if there's other way to generate .profdata file?

**Comment by lxyyyy09** [comment]
And I also changed Cargo.toml to switch to the latest rustc, since I had problems when I use https://github.com/dwrensha/rust.git --branch fuzz.

**Comment by dwrensha** [comment]
I just now updated that branch and pushed https://github.com/dwrensha/fuzz-rustc/commit/b5ed2d31d799f1cf816e5e660bfc1c033b8f33b5 to make things work on the latest rustc.

**Comment by dwrensha** [comment]
I don't know anything about `.profdata` files. Let me know if you figure it out!

**Comment by lxyyyy09** [comment]
I use the branch b5ed2d3 and add`[profile.release]
debug = true
instrument-coverage=true`into Cargo.toml. 
Now my problem is solved.Thanks!

**Comment by cicilzx** [comment]
> I use the branch [b5ed2d3](https://github.com/dwrensha/fuzz-rustc/commit/b5ed2d31d799f1cf816e5e660bfc1c033b8f33b5) and add`[profile.release] debug = true instrument-coverage=true`into Cargo.toml. Now my problem is solved.Thanks!

Hi, I am facing the same problem with you. May I ask where exactly you added `instrument-coverage = true` in your `Cargo.toml`? I’ve tried adding it to both `rustc/Cargo.toml` and `fuzz-rustc/Cargo.toml`, but no `.profraw` files are being generated.

**Comment by lxyyyy09** [comment]
> > I use the branch [b5ed2d3](https://github.com/dwrensha/fuzz-rustc/commit/b5ed2d31d799f1cf816e5e660bfc1c033b8f33b5) and add`[profile.release] debug = true instrument-coverage=true`into Cargo.toml. Now my problem is solved.Thanks!
> 
> Hi, I am facing the same problem with you. May I ask where exactly you added `instrument-coverage = true` in your `Cargo.toml`? I’ve tried adding it to both `rustc/Cargo.toml` and `fuzz-rustc/Cargo.toml`, but no `.profraw` files are being generated.

Sorry, I forgot how to modify the Cargo.toml because the server that hosted the data and scripts crashed. However, if you're trying to obtain code coverage within rustc, you need to add -Cinstrument-coverage to the rustflags in the bootstrap process like RustSmith, then recompile rustc before performing fuzzing. You might also need to disable incremental compilation.
